#!/bin/bash
set -e

PLUGINS_ENDPOINT=http://updates.jenkins-ci.org/latest/
DATA=/var/lib/jenkins

mkdir -p $DATA/plugins
mkdir -p $DATA/jobs

if find $DATA/plugins -maxdepth 0 -empty | read v; then
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/credentials.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/git-client.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/git.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/github.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/scm-api.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/postbuild-task.hpi)
    (cd $DATA/plugins && wget --no-check-certificate -O mule-mmc.hpi https://github.com/adamsdavis1976/misc-binaries/blob/master/mule-mmc.hpi?raw=true)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/build-pipeline-plugin.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/copyartifact.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/ws-cleanup.hpi)
    (cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/extensible-choice-parameter.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/jquery.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/parameterized-trigger.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/workflow-step-api.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/plain-credentials.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/github-api.hpi)
fi

if find $DATA/jobs -maxdepth 0 -empty | read v; then
    (cd $DATA && git clone https://github.com/mulesoft-labs/jenkins-config.git && mv $DATA/jenkins-config/jobs/ $DATA/ && mv $DATA/jenkins-config/*.xml $DATA/ && mv $DATA/jenkins-config/maven_settings/ $DATA/ )
fi

chown -R jenkins $DATA

//exec su jenkins -c "java -jar /usr/share/jenkins/jenkins.war"
